/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package flink.scala.app

import org.apache.flink.api.scala.ExecutionEnvironment
import org.apache.flink.api.scala._

object App {
  case class WordWithCount(word: String, count: Long)

  def main(args: Array[String]): Unit = {
    // 获取执行器的环境
    val env: StreamExecutionEnvironment = StreamExecutionEnvironment.getExecutionEnvironment

    //获取数据: 从socket中获取
    val textDataStream = env.socketTextStream("127.0.0.1", 8888, '\n')
    val tupDataStream = textDataStream.flatMap(_.split(" ")).map(WordWithCount(_,1))

    //groupby: 按照指定的字段聚合
    val windowDstram = tupDataStream.keyBy("word").timeWindow(Time.seconds(5), Time.seconds(1))//窗口bsize=5秒, slid=1s
    windowDstram.sum("count").print()

    //启动执行器，执行程序
    env.execute("Socket Window WordCount")
  }
}
